name: Branch Name Check

on:
  pull_request:
    branches:
      - develop
      - main
    types: [opened, synchronize, edited]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-branch-name:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Get branch names.
      id: branch-names
      uses: tj-actions/branch-names@v8

    - name: Show Output result for source-branch and target-branch
      run: |
        echo "source-branch=${{ steps.branch-names.outputs.head_ref_branch }}"
        echo "target-branch=${{ steps.branch-names.outputs.base_ref_branch }}"

    - name: Check branch name for develop PRs
      id: check-develop-branch
      if: ${{ steps.branch-names.outputs.base_ref_branch == 'develop' }}
      run: |
        if ! [[ "${{ steps.branch-names.outputs.head_ref_branch }}" =~ ^(feature/.*|docs/.*|hotfix/.*|bugfix/.*|release/[0-9]+\.[0-9]+\.[0-9]+(rc[0-9]+)?)$ ]]; then
          echo "reason=Invalid branch name for develop. Branches must follow the GitFlow naming convention." >> $GITHUB_OUTPUT
        fi

    - name: Check branch name for main PRs
      id: check-main-branch
      if: ${{ steps.branch-names.outputs.base_ref_branch == 'main' }}
      run: |
        if ! [[ "${{ steps.branch-names.outputs.head_ref_branch }}" =~ ^(hotfix/.*|release/[0-9]+\.[0-9]+\.[0-9]+(rc[0-9]+)?)$ ]]; then
          echo "reason=Invalid branch name for main. Pull requests must be from a hotfix or release branch." >> $GITHUB_OUTPUT
        fi

    - name: Comment on PR for invalid branch name
      if: ${{ steps.check-develop-branch.outputs.reason || steps.check-main-branch.outputs.reason }}
      run: |
        reason="${{ steps.check-develop-branch.outputs.reason }}${{ steps.check-main-branch.outputs.reason }}"
        gh pr comment ${{ github.event.pull_request.number }} --body "$reason Please review our [branch naming guidelines](LINK_TO_GUIDELINES)."
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Fail if branch name is invalid
      if: ${{ steps.check-develop-branch.outputs.reason || steps.check-main-branch.outputs.reason }}
      run: |
        echo "Invalid branch name. Please review our branch naming guidelines."
        exit 1