name: Branch Name Check

on:
  pull_request:
    branches:
      - develop
      - main
    types: [opened, synchronize, edited]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-branch-name:
    runs-on: ubuntu-latest
    steps:
    - name: Get branch names.
      id: branch-names
      uses: tj-actions/branch-names@v8

    - name: Show Output result for source-branch and target-branch
      run: |
        echo "source-branch=${{ steps.branch-names.outputs.head_ref_branch }}"
        echo "target-branch=${{ steps.branch-names.outputs.base_ref_branch }}"

    - name: Check branch name for develop PRs
      if: ${{ steps.branch-names.outputs.base_ref_branch == 'develop' }}
      run: |
        if ! [[ "${{ steps.branch-names.outputs.head_ref_branch }}" =~ ^(feature/.*|docs/.*|hotfix/.*|bugfix/.*|release/[0-9]+\.[0-9]+\.[0-9]+(rc[0-9]+)?)$ ]]; then
          echo "REASON=Invalid branch name for develop. Branches must follow the GitFlow naming convention." >> $GITHUB_ENV
        fi

    - name: Check branch name for main PRs
      if: ${{ steps.branch-names.outputs.base_ref_branch == 'main' }}
      run: |
        if ! [[ "${{ steps.branch-names.outputs.head_ref_branch }}" =~ ^(hotfix/.*|release/[0-9]+\.[0-9]+\.[0-9]+(rc[0-9]+)?)$ ]]; then
          echo "REASON=Invalid branch name for main. Pull requests must be from a hotfix or release branch." >> $GITHUB_ENV
        fi

    - name: Comment on PR for invalid branch name
      if: env.REASON != ''
      run: |
        gh pr comment ${{ github.event.pull_request.number }} --body "${{ env.REASON }} Please review our [branch naming guidelines](LINK_TO_GUIDELINES)."
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
