name: Trigger Build on Release and PRs to Main

on:
  push:
    branches:
      - release/*
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  trigger-build:
    